name: Send GitHub Action trigger data to Slack workflow

on:
  push:
    branches:
      - main
      - github_actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        run: >-
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
        uses: slackapi/slack-github-action@v1.21.0
#         with:
# #           token: ${{ secrets.SLACK_WEBHOOK_URL }}
# #           path: app/build/outputs/apk/debug/app-debug.apk
# #           channel: "#test-github-action"
# #           title: "Github actions release apk"
#             payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
          channel: "#test-github-action"
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          run: |  
          curl -F file=@app-debug.apk -F "initial_comment=Github Action Release APK" -F channels=C0R7MFNJD -H "Authorization: Bearer xoxp-123456789" https://slack.com/api/files.upload

#       - name: Upload to slack step
#         uses: adrey/slack-file-upload-action@master
#         with:
#           token: ${{ secrets.SLACK_WEBHOOK_URL }}
#           path: app/build/outputs/apk/debug/app-debug.apk
#           channel: "#test-github-action"
#           title: "Github actions release apk"
